# Generated by Django 5.2.7 on 2025-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_asistio', 'No Asistió')], default='agendada', max_length=15, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo de la Cita')),
                ('url_teams', models.URLField(blank=True, null=True, verbose_name='URL de Teams')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('disponible', models.BooleanField(default=True, help_text='Desmarcar para bloquear este horario', verbose_name='Disponible')),
                ('motivo', models.CharField(blank=True, help_text='Razón del bloqueo (si aplica)', max_length=200, null=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Disponibilidad Horaria',
                'verbose_name_plural': 'Disponibilidades Horarias',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interaccion', models.CharField(editable=False, max_length=50, unique=True, verbose_name='ID de Interacción')),
                ('resultado', models.CharField(choices=[('efectiva', 'Efectiva'), ('no_asiste', 'No Asiste')], max_length=15, verbose_name='Resultado')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
