# Generated by Django 5.2.7 on 2025-11-03 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadhoraria',
            unique_together={('fecha', 'hora_inicio')},
        ),
        migrations.AddField(
            model_name='interaccion',
            name='asesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacciones_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interaccion', to='citas.cita', verbose_name='Cita'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='citas_cita_fecha_49634a_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['usuario', 'estado'], name='citas_cita_usuario_b33a3a_idx'),
        ),
    ]
