# Generated by Django 5.2.7 on 2025-11-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_solicitante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='teams_creado_en',
            field=models.DateTimeField(blank=True, help_text='Timestamp de cuándo se creó la reunión de Teams', null=True, verbose_name='Fecha de Creación de Teams'),
        ),
        migrations.AddField(
            model_name='cita',
            name='teams_event_id',
            field=models.CharField(blank=True, help_text='ID interno del evento de Teams en Microsoft Calendar', max_length=200, null=True, verbose_name='ID del Evento en Microsoft Graph'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='url_teams',
            field=models.URLField(blank=True, help_text='URL de la reunión de Teams (generada automáticamente)', max_length=500, null=True, verbose_name='Enlace de Microsoft Teams'),
        ),
    ]
