# Generated by Django 5.2.7 on 2025-11-05 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PEP', 'Permiso Especial de Permanencia'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte')], max_length=5, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(db_index=True, max_length=20, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Intersexual')], max_length=1, verbose_name='Sexo')),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, verbose_name='Género')),
                ('orientacion_sexual', models.CharField(choices=[('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual'), ('bisexual', 'Bisexual'), ('pansexual', 'Pansexual'), ('asexual', 'Asexual'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], max_length=20, verbose_name='Orientación Sexual')),
                ('rango_edad', models.CharField(choices=[('0-17', '0-17 años'), ('18-25', '18-25 años'), ('26-35', '26-35 años'), ('36-45', '36-45 años'), ('46-55', '46-55 años'), ('56-65', '56-65 años'), ('66+', '66 años o más')], max_length=10, verbose_name='Rango de Edad')),
                ('nivel_educativo', models.CharField(choices=[('ninguno', 'Ninguno'), ('primaria', 'Primaria'), ('bachillerato', 'Bachillerato'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('profesional', 'Profesional'), ('postgrado', 'Postgrado')], max_length=20, verbose_name='Nivel Educativo')),
                ('grupo_etnico', models.CharField(choices=[('ninguno', 'Ninguno'), ('indigena', 'Indígena'), ('rom', 'ROM (Gitano)'), ('raizal', 'Raizal'), ('palenquero', 'Palenquero'), ('negro', 'Negro(a) / Afrocolombiano(a)')], max_length=20, verbose_name='Grupo Étnico')),
                ('grupo_poblacional', models.CharField(choices=[('ninguno', 'Ninguno'), ('victima_conflicto', 'Víctima del conflicto armado'), ('desplazado', 'Desplazado'), ('reinsertado', 'Reinsertado'), ('habitante_calle', 'Habitante de calle'), ('lgbtiq', 'LGBTIQ+'), ('migrante', 'Migrante'), ('otro', 'Otro')], max_length=30, verbose_name='Grupo Poblacional')),
                ('estrato_socioeconomico', models.CharField(choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, verbose_name='Estrato Socioeconómico')),
                ('localidad', models.CharField(choices=[('usaquen', 'Usaquén'), ('chapinero', 'Chapinero'), ('santa_fe', 'Santa Fe'), ('san_cristobal', 'San Cristóbal'), ('usme', 'Usme'), ('tunjuelito', 'Tunjuelito'), ('bosa', 'Bosa'), ('kennedy', 'Kennedy'), ('fontibon', 'Fontibón'), ('engativa', 'Engativá'), ('suba', 'Suba'), ('barrios_unidos', 'Barrios Unidos'), ('teusaquillo', 'Teusaquillo'), ('los_martires', 'Los Mártires'), ('antonio_narino', 'Antonio Nariño'), ('puente_aranda', 'Puente Aranda'), ('candelaria', 'La Candelaria'), ('rafael_uribe', 'Rafael Uribe Uribe'), ('ciudad_bolivar', 'Ciudad Bolívar'), ('sumapaz', 'Sumapaz'), ('fuera_bogota', 'Fuera de Bogotá')], max_length=30, verbose_name='Localidad')),
                ('calidad_comunicacion', models.CharField(choices=[('propio', 'Propio'), ('familiar', 'Familiar'), ('amigo', 'Amigo'), ('representante_legal', 'Representante Legal'), ('otro', 'Otro')], max_length=30, verbose_name='Te comunicas en calidad de')),
                ('tiene_discapacidad', models.BooleanField(default=False, verbose_name='¿Tienes alguna discapacidad?')),
                ('tipo_discapacidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de discapacidad (si aplica)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='citas_cita_usuario_b33a3a_idx',
        ),
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema (solo para asesores/admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='citas_solic_tipo_do_a33e08_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['numero_documento'], name='citas_solic_numero__b60e90_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['correo_electronico'], name='citas_solic_correo__5e4b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitante',
            index=models.Index(fields=['-fecha_registro'], name='citas_solic_fecha_r_bc3889_idx'),
        ),
        migrations.AddField(
            model_name='cita',
            name='solicitante',
            field=models.ForeignKey(blank=True, help_text='Persona que solicita la cita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.solicitante', verbose_name='Solicitante'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_cita_estado_2000d2_idx'),
        ),
    ]
